SELECT * FROM customer_behaviour_analysis;

ALTER TABLE customer_behaviour_analysis
RENAME to shopping;

SELECT *  FROM shopping;


----------------------------------------------------------------------------------------------------------------
--Business insights Questions
----------------------------------------------------------------------------------------------------------------

--1. Which category generates highest revenue?
SELECT category,  ROUND(SUM(purchase_amount)::numeric,2) AS highest_revenue FROM shopping
GROUP BY category
ORDER BY highest_revenue DESC LIMIT 5;

--? Business problem :- Company does not know which category contributes most to revenue. 


--2. Are discount actually increasing purchase value?

SELECT discount_applied,ROUND(SUM(purchase_amount)::numeric,2) AS total_sales FROM shopping
GROUP BY discount_applied;

--? Business Problem :Discount may reduce profit without increasing sales

--3. What is the total revenue generated by male and female?
SELECT gender,ROUND(SUM(purchase_amount)::numeric,2) AS total_sales FROM shopping
GROUP BY gender;

--? Business Problem :- Lack of understanding of revenue contribution by gender segment 

--4 Which customer used a discount but still spent more then the average purchase amount?

SELECT 
	customer_id,
	discount_applied,
	purchase_amount
	FROM shopping
	WHERE discount_applied ='Yes' AND purchase_amount>(SELECT AVG(purchase_amount) FROM shopping);

--? Business Problem :- Company cannot identify high-spending customer who are also using discount

--5 which are the top/bottom 5 products with the highest average review rating


SELECT item_purchased ,ROUND(AVG(review_rating)::numeric,2) AS avg_sales FROM shopping
GROUP BY item_purchased
ORDER BY  avg_sales DESC LIMIT 5;


--? Business Problem :- No visibility into product performance based on customer satisfaction

--6 Averagr purchase : Stabdard vs Express shipping


SELECT shipping_type,
	COUNT(DISTINCT customer_id) as order_placed,
	ROUND(AVG(purchase_amount)::numeric,2) as avg_purchase
	FROM shopping 
	WHERE shipping_type IN ('Standard','Express')
	GROUP BY shipping_type;

--? Business Problem :- Unclear if faster shipping leads to highe spending


--7. Do subscribed customer spend more ? Compare average speed and total revenue 
--between  subscribers and non subscribers

SELECT subscription_status,ROUND(SUM(purchase_amount)::numeric,2) AS Total_revenue,
ROUND(AVG(purchase_amount)::numeric,2) AS average_revenue FROM shopping
GROUP BY subscription_status;

--? Business Probelm :- The effectiveness of subscription program is unknown

--8. Top 5 products with highest discount usage%

SELECT item_purchased ,
COUNT(item_purchased) AS Total_number_of_time_sold,
COUNT(CASE WHEN(discount_applied='Yes') THEN 1 END) AS Number_of_time_sold_when_discount_applied,
COUNT(CASE WHEN(discount_applied='Yes') THEN 1 END) * 100.0/ COUNT(*) AS discount_percent
FROM shopping
GROUP BY item_purchased
ORDER BY discount_percent DESC LIMIT 5;

--? Business Problem :- Some of products may be overly dependent on discounts.



--9. Segment customer into new ,returning and loyal based on thier total number of previous purchase and 
-- show the count of each segment

SELECT 
	CASE
		WHEN previous_purchases= 0 THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer  '
		ELSE 'Loyal Customer '
	END AS Customer_segment ,
	COUNT(*) AS customer_count
	FROM shopping
	GROUP BY Customer_segment;


--? Business Problem :- Lack of customer segmentation leads to generic strategies


--10 What are the top three most purchased products within each category ?


WITH CTE AS
(
SELECT item_purchased,category,COUNT(item_purchased) AS number_of_purchased,
RANK() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
FROM shopping
GROUP BY item_purchased,category
)
SELECT * FROM CTE
WHERE RNK<=3;

--?Business Problem :- The company doesn,t know top -performing products within categories.

--11. Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe


SELECT CASE
			WHEN previous_purchases>5 THEN 'Repeat Buyers'
			ELSE 'Normal Buyers'
		END AS customer_type,subscription_status,
		COUNT(*) AS customer_count,
		COUNT(*) * 100/ SUM(COUNT(*)) OVER (PARTITION BY CASE
			WHEN previous_purchases>5 THEN 'Repeat Buyers'
			ELSE 'Normal Buyers'
		END ) AS percents
		
		FROM shopping
		GROUP BY customer_type,subscription_status;

--? Business Problem :- Unclear relationship between loyality and subscription 

--12 What is the revenue contribution of each age group?
SELECT * FROM shopping;

SELECT CASE
			WHEN age BETWEEN 18 AND 25 THEN '18-25'
			WHEN age BETWEEN 26 AND 35 THEN '26-35'
			WHEN age BETWEEN 36 AND 50 THEN '36-50'
			ELSE '51+'
			END AS age_group ,
			ROUND(SUM(purchase_amount)::numeric,2) AS total_revenue
			FROM shopping
	GROUP BY age_group
	ORDER BY total_revenue DESC;

--? Business Problem :- No visibility into which age group contributes most of revenue